version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6

  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - static:/backend_static
      - media:/app/media
      - ./backend/:/backend

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./backend/:/backend
    links:
      - redis
    depends_on:
      - redis

  nginx:
    build: ./nginx/
    depends_on:
      - backend
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - media:/media
      - static:/backend_static