# Generated by Django 4.2 on 2024-08-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_remove_component_product'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='component',
            field=models.ManyToManyField(to='components.component', verbose_name='Компонент'),
        ),
    ]
