# Generated by Django 4.2 on 2024-08-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_alter_component_component_link'),
        ('products', '0003_product_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='component',
        ),
        migrations.AddField(
            model_name='product',
            name='components',
            field=models.ManyToManyField(blank=True, to='components.component', verbose_name='Компонент'),
        ),
    ]
