# Generated by Django 4.2 on 2024-08-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_alter_component_component_link'),
        ('products', '0004_remove_product_component_product_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='components',
        ),
        migrations.AlterField(
            model_name='product',
            name='parent_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_product', to='products.product', verbose_name='Родительский продукт'),
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.component', verbose_name='Компонент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'компонент продукта',
                'verbose_name_plural': 'Компоненты продуктов',
            },
        ),
        migrations.AddConstraint(
            model_name='productcomponent',
            constraint=models.UniqueConstraint(fields=('product', 'component'), name='unique_product_component'),
        ),
    ]
