# Generated by Django 4.2 on 2024-08-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_alter_component_component_link'),
        ('products', '0005_remove_product_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='components',
            field=models.ManyToManyField(blank=True, through='products.ProductComponent', to='components.component', verbose_name='Компонент'),
        ),
    ]
