# Generated by Django 4.2 on 2024-08-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_components'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomponent',
            options={'default_related_name': 'productcomponent', 'verbose_name': 'компонент продукта', 'verbose_name_plural': 'Компоненты продуктов'},
        ),
    ]
