# Generated by Django 4.2 on 2024-08-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productcomponent_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_description'], name='products_pr_product_8d4979_idx'),
        ),
    ]
