# Generated by Django 4.2 on 2024-08-07 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Содержание поля')),
            ],
            options={
                'verbose_name': 'компонент',
                'verbose_name_plural': 'Компоненты',
                'default_related_name': 'component',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('component_type', models.CharField(max_length=150, verbose_name='Тип')),
                ('component_link', models.URLField(verbose_name='Ссылка на документацию')),
                ('component_description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'компонент',
                'verbose_name_plural': 'Компоненты',
                'default_related_name': 'component',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Содержание метрики')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'метрика',
                'verbose_name_plural': 'Метрики',
                'default_related_name': 'metric',
            },
        ),
    ]
