# Generated by Django 4.2 on 2024-07-31 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament_name', models.CharField(max_length=250, verbose_name='Название')),
                ('departament_description', models.TextField(verbose_name='Описание отдела')),
                ('departament_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Руководитель департамента')),
                ('parent_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.department', verbose_name='Родительский департамент')),
            ],
            options={
                'verbose_name': 'департамент',
                'verbose_name_plural': 'Департаменты',
                'default_related_name': 'departament',
            },
        ),
    ]
