# Generated by Django 4.2 on 2024-08-03 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Содержание поля')),
            ],
            options={
                'verbose_name': 'компонент',
                'verbose_name_plural': 'Компоненты',
                'default_related_name': 'component',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=250, verbose_name='Название')),
                ('component_type', models.CharField(max_length=150, verbose_name='Тип')),
                ('component_link', models.URLField(verbose_name='Ссылка на документацию')),
                ('component_description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'компонент',
                'verbose_name_plural': 'Компоненты',
                'default_related_name': 'component',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament_name', models.CharField(max_length=250, verbose_name='Название')),
                ('departament_description', models.TextField(verbose_name='Описание отдела')),
            ],
            options={
                'verbose_name': 'департамент',
                'verbose_name_plural': 'Департаменты',
                'default_related_name': 'departament',
            },
        ),
        migrations.CreateModel(
            name='GazpromUserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='Роль сотрудника в команде')),
            ],
            options={
                'verbose_name': 'роль сотрудника в команде',
                'verbose_name_plural': 'Роли сотрудников в командах',
                'default_related_name': 'gazpromuserteam',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Содержание метрики')),
            ],
            options={
                'verbose_name': 'метрика',
                'verbose_name_plural': 'Метрики',
                'default_related_name': 'metric',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, verbose_name='Название')),
                ('product_description', models.TextField(verbose_name='Описание продукта')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'Продукты',
                'default_related_name': 'product',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=250, verbose_name='Название')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.product', verbose_name='Родительский продукт')),
            ],
            options={
                'verbose_name': 'команда',
                'verbose_name_plural': 'Команды',
                'default_related_name': 'team',
            },
        ),
    ]
