# Generated by Django 4.2 on 2024-08-01 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, verbose_name='Название')),
                ('product_description', models.TextField(verbose_name='Описание продукта')),
                ('parent_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.product', verbose_name='Родительский продукт')),
                ('product_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер продукта')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'Продукты',
                'default_related_name': 'product',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=250, verbose_name='Название')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.product', verbose_name='Родительский продукт')),
                ('team_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер команды')),
            ],
            options={
                'verbose_name': 'команда',
                'verbose_name_plural': 'Команды',
                'default_related_name': 'team',
            },
        ),
        migrations.CreateModel(
            name='GazpromUserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='Роль сотрудника в команде')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'роль сотрудника в команде',
                'verbose_name_plural': 'Роли сотрудников в командах',
                'default_related_name': 'gazpromuserteam',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=250, verbose_name='Название')),
                ('component_type', models.CharField(max_length=150, verbose_name='Тип')),
                ('component_link', models.URLField(verbose_name='Ссылка на документацию')),
                ('component_description', models.TextField(verbose_name='Описание')),
                ('component_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_components', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за компонент')),
                ('component_second_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_owned_components', to=settings.AUTH_USER_MODEL, verbose_name='Заместитель ответственного за компонент')),
            ],
            options={
                'verbose_name': 'компонент',
                'verbose_name_plural': 'Компоненты',
                'default_related_name': 'component',
            },
        ),
    ]
