# Generated by Django 4.2 on 2024-08-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Component',
        ),
    ]
