# Generated by Django 4.2 on 2024-08-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='department',
            name='departament_name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('id', 'parent_department'), name='Department cannot be a parent to itself'),
        ),
        migrations.AddConstraint(
            model_name='gazpromuserteam',
            constraint=models.UniqueConstraint(fields=('employee', 'team', 'role'), name='Unique employee role in team'),
        ),
    ]
