# Generated by Django 4.2 on 2024-08-01 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('company', '0002_product_team_gazpromuserteam_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Содержание метрики')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'метрика',
                'verbose_name_plural': 'Метрики',
                'default_related_name': 'metric',
            },
        ),
        migrations.CreateModel(
            name='AdditionalFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Содержание поля')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'компонент',
                'verbose_name_plural': 'Компоненты',
                'default_related_name': 'component',
            },
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['content_type', 'object_id'], name='company_met_content_24f8ca_idx'),
        ),
        migrations.AddIndex(
            model_name='additionalfields',
            index=models.Index(fields=['content_type', 'object_id'], name='company_add_content_c24c7f_idx'),
        ),
    ]
