# Generated by Django 4.2 on 2024-08-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_delete_component'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalfield',
            options={'default_related_name': 'additionalfield', 'verbose_name': 'дополнительное поле', 'verbose_name_plural': 'Дополнительные поля'},
        ),
    ]
