# Generated by Django 4.2 on 2024-08-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('company', '0003_metric_additionalfields_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalFields',
            new_name='AdditionalField',
        ),
        migrations.RenameIndex(
            model_name='additionalfield',
            new_name='company_add_content_cdcf27_idx',
            old_name='company_add_content_c24c7f_idx',
        ),
    ]
