# Generated by Django 4.2 on 2024-08-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_component_component_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='Department cannot be a parent to itself',
        ),
    ]
