# Generated by Django 4.2 on 2024-08-18 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("departments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="departament_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Руководитель департамента",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="parent_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children_departament",
                to="departments.department",
                verbose_name="Родительский департамент",
            ),
        ),
    ]
