# Generated by Django 4.2 on 2024-08-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='departament_name',
            new_name='name',
        ),
    ]
