# Generated by Django 4.2 on 2024-08-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_rename_departament_name_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='departament_name',
        ),
    ]
