# Generated by Django 4.2 on 2024-08-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_rename_name_department_departament_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['departament_description'], name='departments_departa_7b3d75_idx'),
        ),
    ]
