# Generated by Django 4.2 on 2024-08-07 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('component_type', models.CharField(max_length=150, verbose_name='Тип')),
                ('component_link', models.URLField(verbose_name='Ссылка на документацию')),
                ('component_description', models.TextField(verbose_name='Описание')),
                ('component_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_components', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за компонент')),
                ('component_second_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_owned_components', to=settings.AUTH_USER_MODEL, verbose_name='Заместитель ответственного за компонент')),
            ],
            options={
                'verbose_name': 'компонент',
                'verbose_name_plural': 'Компоненты',
                'default_related_name': 'component',
            },
        ),
    ]
