# Generated by Django 4.2 on 2024-08-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('component_type', models.CharField(max_length=150, verbose_name='Тип')),
                ('component_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на документацию')),
                ('component_description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'компонент',
                'verbose_name_plural': 'Компоненты',
                'default_related_name': 'component',
            },
        ),
    ]
