# Generated by Django 4.2 on 2024-08-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='product',
            field=models.ManyToManyField(to='products.product', verbose_name='Продукт'),
        ),
    ]
