# Generated by Django 4.2 on 2024-08-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_component_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='product',
        ),
    ]
