# Generated by Django 4.2 on 2024-08-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_alter_component_component_link'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['component_description'], name='components__compone_5bd1d7_idx'),
        ),
    ]
