# Generated by Django 4.2 on 2024-08-18 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0003_alter_department_departament_owner_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gazpromuser",
            name="employee_departament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="departments.department",
                verbose_name="Департамент",
            ),
        ),
    ]
