# Generated by Django 4.2 on 2024-08-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gazpromuser',
            name='skills',
            field=models.ManyToManyField(blank=True, to='users.skill', verbose_name='Навыки'),
        ),
    ]
