# Generated by Django 4.2 on 2024-08-11 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'навык сотрудника',
                'verbose_name_plural': 'Навыки сотрудников',
            },
        ),
        migrations.RemoveField(
            model_name='gazpromuser',
            name='skills',
        ),
        migrations.AddIndex(
            model_name='gazpromuser',
            index=models.Index(fields=['employee_fio'], name='users_gazpr_employe_d53b37_idx'),
        ),
        migrations.AddIndex(
            model_name='gazpromuser',
            index=models.Index(fields=['employee_position'], name='users_gazpr_employe_102259_idx'),
        ),
        migrations.AddIndex(
            model_name='gazpromuser',
            index=models.Index(fields=['employee_telegram'], name='users_gazpr_employe_c82d51_idx'),
        ),
        migrations.AddIndex(
            model_name='gazpromuser',
            index=models.Index(fields=['employee_telephone'], name='users_gazpr_employe_e796c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='gazpromuser',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_telegram', None), _negated=True), fields=('employee_telegram',), name='unique_employee_telegram'),
        ),
        migrations.AddConstraint(
            model_name='gazpromuser',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_telephone', None), _negated=True), fields=('employee_telephone',), name='unique_employee_telephone'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.skill', verbose_name='Навык'),
        ),
        migrations.AddConstraint(
            model_name='employeeskill',
            constraint=models.UniqueConstraint(fields=('employee', 'skill'), name='unique_employee_skill'),
        ),
    ]
