# Generated by Django 4.2 on 2024-08-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_gazpromuser_employee_departament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gazpromuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Адрес электронной почты'),
        ),
    ]
