# Generated by Django 4.2 on 2024-08-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employeeskill_remove_gazpromuser_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gazpromuser',
            name='skills',
            field=models.ManyToManyField(blank=True, through='users.EmployeeSkill', to='users.skill', verbose_name='Навыки'),
        ),
    ]
