# Generated by Django 4.2 on 2024-08-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_gazpromuser_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gazpromuser',
            name='username',
        ),
    ]
