# Generated by Django 4.2 on 2024-08-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_gazpromuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gazpromuser',
            name='employee_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
