# Generated by Django 4.2 on 2024-08-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_gazpromuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gazpromuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Логин пользователя'),
        ),
    ]
