# Generated by Django 4.2 on 2024-08-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_gazpromuser_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeskill',
            options={'default_related_name': 'employeeskill', 'verbose_name': 'навык сотрудника', 'verbose_name_plural': 'Навыки сотрудников'},
        ),
    ]
