# Generated by Django 4.2 on 2024-08-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_employeeskill_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gazpromuser',
            index=models.Index(fields=['employee_grade'], name='users_gazpr_employe_64f9d1_idx'),
        ),
        migrations.AddIndex(
            model_name='gazpromuser',
            index=models.Index(fields=['employee_location'], name='users_gazpr_employe_3ad0bb_idx'),
        ),
    ]
