# Generated by Django 4.2 on 2024-08-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_gazpromuser_employee_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gazpromuser',
            name='employee_type_job',
            field=models.CharField(blank=True, choices=[('full_time', 'полная занятость'), ('part_time', 'частичная занятость'), ('internship', 'стажировка')], max_length=50, null=True, verbose_name='Тип занятости'),
        ),
    ]
