# Generated by Django 4.2 on 2024-08-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_gazpromuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gazpromuser',
            managers=[
            ],
        ),
    ]
