# Generated by Django 4.2 on 2024-08-01 18:01

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_gazpromuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gazpromuser',
            name='employee_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='gazpromuser',
            name='employee_date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[users.validators.validate_birth_date], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='gazpromuser',
            name='employee_date_of_hire',
            field=models.DateField(blank=True, null=True, validators=[users.validators.validate_hire_date], verbose_name='Дата найма'),
        ),
        migrations.AlterField(
            model_name='gazpromuser',
            name='employee_description',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='gazpromuser',
            name='employee_grade',
            field=models.CharField(blank=True, choices=[('1', 'Gr-1'), ('2', 'Gr-2'), ('3', 'Gr-3'), ('4', 'Gr-4'), ('5', 'Gr-5'), ('6', 'Gr-6'), ('7', 'Gr-7')], max_length=50, null=True, verbose_name='Грейд'),
        ),
        migrations.AlterField(
            model_name='gazpromuser',
            name='employee_location',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='gazpromuser',
            name='employee_position',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='gazpromuser',
            name='employee_status',
            field=models.CharField(blank=True, choices=[('working', 'в работе'), ('vacation', 'отпуск'), ('sick', 'больничный'), ('fired', 'уволен')], max_length=50, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='gazpromuser',
            name='employee_telegram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='gazpromuser',
            name='employee_telephone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен начинаться с + и состоять из 10-15 цифр', regex='^\\+\\d{10,15}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='gazpromuser',
            name='employee_type_job',
            field=models.CharField(blank=True, choices=[('full_time', 'полная занятость'), ('part_time', 'частичная занятость'), ('full_time', 'полная занятость'), ('full_time', 'полная занятость')], max_length=50, null=True, verbose_name='Тип занятости'),
        ),
    ]
